@startuml
'https://plantuml.com/class-diagram



class MainActivity {
    +onCreate(Bundle savedInstanceState) : void
}

class ListActivity {
    +onCreate(Bundle savedInstanceState) : void
}

class AddTodoActivity {
    +onCreate(Bundle savedInstanceState) : void
}

@enduml